# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e437c618d12ac24023d6f366e84cae6575ac5b0552ce4f921ee83d4d789589241c81988c1ddd710ccb2ce79b0cf042574ced1856c62df2426ad6acb20689f245

test:
  secret_key_base: 6b2d5f2b8fb9faa423002f1d854cf2c8723c34c6fbac7ad775873778b236c29b456653002008e1d00f6f03cfaff561fa13907e748e8a01f7756330dce16fed12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
